### ISSUE TITLE
Create messagesDelete.js

### ISSUE THREAD

**Issue by Adobe-Android** [nss-day-cohort-20/group-project-chatty-gitittogether#10]
Accepts the element id "messages-output"
Removes only the correct element from the DOM
Removes the same element from the private array

**Comment by AspenHumphrey** [comment]
The shell of the messagesDelete.js has been created with "functionality needed" and in iffe format.... we need the messagesAdd.js info in order to properly run/ invoke/ test messagesDelete.js
